name: Create Prompt

on:
  workflow_dispatch:
    inputs:
      task:
        description: 'Task description'
        required: true
        type: string

jobs:
  generate_prompt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate prompt
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python ./main.py create-prompt "${{ github.event.inputs.task }}"
