name: Create Agent

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'Agent description/goal'
        required: true
        type: string

jobs:
  install-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run create-swarm-agent
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python main.py create-swarm-agent "${{ github.event.inputs.description }}"
