name: Generate Prompt

on:
  workflow_dispatch:
    inputs:
      task:
        description: 'Task description'
        required: true
        type: string

jobs:
  generate_prompt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate prompt
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python cli/main.py create-prompt "${{ github.event.inputs.task }}"