name: Install and Run

on:
  workflow_dispatch:

jobs:
  install-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run create-swarm-agent
      run: |
        python cli/main.py create-swarm-agent "Your goal here" --output print
